name: Calculator CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Verify Python
        run: python --version

      - name: Run calculator tests
        run: python -m unittest discover -s tests

      - name: Run Ruff lint
        uses: astral-sh/ruff-action@v3

      - name: Build Docker image
        run: |
          docker build \
            --build-arg APP_VERSION=${{ github.sha }} \
            -t calculator:${{ github.sha }} .

      - name: Run Docker container
        run: |
          docker run \
            --rm \
            calculator:${{ github.sha }} \
            "2+3*4"

      - name: Smoke test
        run: |
          output=$(docker run --rm calculator:${{ github.sha }} "2+3*4")
          echo "$output"
          test "$output" = "result: 14"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag \
            calculator:${{ github.sha }} \
            ghcr.io/${{ github.repository }}:${{ github.sha }}

          docker push \
            ghcr.io/${{ github.repository }}:${{ github.sha }}
